# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Plugin CDK Stack

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: us-east-1
  PLUGIN_ID: react-next-starter

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout plugin repo (this repository)
        uses: actions/checkout@v3

      - name: Install aws-cdk CLI
        run: npm install -g aws-cdk@latest

      - name: Install project dependencies
        run: "yarn install"
      
      - name: Build plugin /dist directory
        run: "yarn build"

      - name: Checkout codotype-api repo (encapsulates CDK stack)
        uses: actions/checkout@v3
        with:
          repository: "codotype/codotype-api"
          path: "codotype-api"

      - name: Install codotype-api CDK stack dependencies
        run: "yarn --cwd ./codotype-api install"

      - name: "Install generate-endpoint AWS Lambda dependencies"
        run: "yarn --cwd ./codotype-api/src/generate-endpoint install && cp -R ./dist ./codotype-api/src/generate-endpoint/plugin"

      - name: "Install plugins-endpoint AWS Lambda dependencies"
        run: "yarn --cwd ./codotype-api/src/plugins-endpoint install && cp -R ./dist ./codotype-api/src/plugins-endpoint/plugin"

      - name: "Install preview-endpoint AWS Lambda dependencies"
        run: "yarn --cwd ./codotype-api/src/preview-endpoint install && cp -R ./dist ./codotype-api/src/preview-endpoint/plugin"

      - name: "Build CDK Stack"
        run: "yarn --cwd ./codotype-api build"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CDK stack
        run: cd ./codotype-api && cdk deploy --require-approval never
